name: main.yml
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.dart'

jobs:
  Build_Web_Project:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.4'
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Web
        # The repository name shouldn't be hardcoded but since the scope of the project is fairly simple, so it's cool.
        # Just keep in mind that incase you change the repo name, it will break the CI/CD Pipeline
        run: flutter build web --base-href /Personal-Portfolio/
      - name: Upload Web Build Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web/

  Deploy_Web_Project:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Build_Web_Project
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

